apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep
  namespace: "{{ .Values.namespace }}"
  labels:
    app: busybox-sleep
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
