apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep
  namespace: "{{ .Values.namespace }}"
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - sleep
    - "{{ .Values.sleep_secs }}"
