apiVersion: v1
kind: Pod
metadata:
  name: fluxcd-demo
  namespace: "{{ .Values.namespace }}"
  labels:
    app: fluxcd-demo
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
